- project:
    check:
      jobs:
        - f34-clang-tsan:
            pre-run: ci/pre.yaml
            required-projects: &projects
              - name: github/CESNET/libyang
                override-checkout: devel
              - name: github/sysrepo/sysrepo
                override-checkout: devel
              - name: github/onqtam/doctest
                override-checkout: cesnet/fix-gcc11
              - name: github/rollbear/trompeloeil
                override-checkout: v41
              - name: CzechLight/libyang-cpp
