- project:
    check:
      jobs:
        - f38-gcc-cover:
            required-projects:
              - name: github/CESNET/libyang
                override-checkout: cesnet/2024-03--v2-latest
              - name: github/sysrepo/sysrepo
                override-checkout: cesnet/2024-03--v2-latest
              - name: github/onqtam/doctest
                override-checkout: v2.4.8
              - name: github/rollbear/trompeloeil
                override-checkout: v44
              - name: CzechLight/libyang-cpp
        - f38-clang-asan-ubsan:
            required-projects: &projects
              - name: github/CESNET/libyang
                override-checkout: cesnet/2024-03--v2-latest
              - name: github/sysrepo/sysrepo
                override-checkout: cesnet/2024-03--v2-latest
              - name: github/onqtam/doctest
                override-checkout: v2.4.11
              - name: github/rollbear/trompeloeil
                override-checkout: v44
              - name: CzechLight/libyang-cpp
        - f38-clang-tsan:
            required-projects: *projects
        - clang-format:
            voting: false
        - f38-cpp-coverage-diff:
            voting: false
        - f38-gcc-cover-previous:
            required-projects: *projects
